
  num_jobs: 1
  env_config_path: /configs/ur10_cfg.yaml
  jobs: [
  {algo: PPO, algo_config_path: ./configs/ppo_cfg.yaml,     weight:  None},
  {algo: PPO, algo_config_path: ./configs/ppo_cfg2.yaml,     weight:  None},
  {algo: PPO, algo_config_path: ./configs/ppo_cfg1.yaml,     weight:  None},
  {algo: PPO, algo_config_path: ./configs/ppo_cfg3.yaml,     weight:  None},
  
  {algo: PPO, algo_config_path: ./configs/ppo_cfg1.yaml,     weight:  None},
  {algo: DDPG, algo_config_path: ./configs/ppo_cfg.yaml  ,  weight:  None},
  {algo: TD3, algo_config_path: ./configs/ppo_cfg.yaml   ,  weight:  None},  
  {algo: TD3, algo_config_path: ./configs/ppo_cfg.yaml   ,  weight:  None},  
  {algo: TD3, algo_config_path: ./configs/ppo_cfg.yaml   ,  weight:  None},  
  {algo: TD3, algo_config_path: ./configs/ppo_cfg.yaml   ,  weight:  None},  

  {algo: TRPO, algo_config_path: ./configs/TRPO_cfg.yaml,    weight:  None},  
  {algo: DDPG, algo_config_path: ./configs/ppo_cfg.yaml  ,  weight:  None},
  {algo: TRPO, algo_config_path: ./configs/TRPO_cfg.yaml,    weight:  "./log/TRPO_9/model_04_14_2020_17:31:07.pkl"},  
  {algo: TRPO, algo_config_path: ./configs/TRPO_cfg1.yaml,   weight:  None},
  {algo: TRPO, algo_config_path: ./configs/TRPO_cfg3.yaml,   weight:  None},
  {algo: TRPO, algo_config_path: ./configs/TRPO_cfg4.yaml,   weight:  None},
  {algo: PPO, algo_config_path: ./configs/ppo_cfg.yaml,     weight:  None},
  {algo: PPO, algo_config_path: ./configs/ppo_cfg1.yaml,     weight:  None},
  {algo: PPO, algo_config_path: ./configs/ppo_cfg.yaml,     weight:  None},
  {algo: TRPO, algo_config_path: ./configs/TRPO_cfg.yaml,   weight:  None},
  {algo: TRPO, algo_config_path: ./configs/TRPO_cfg.yaml,   weight:  None},
  ]
