
  num_envs: 1
  
  ent_coef: 0.00 # ent_coef: (float) Entropy coefficient for the loss calculation
  
  total_timesteps: 13000000
  validate_every_timesteps: 30000
  verbose: 1
  gamma: 0.99 #gamma: (float) Discount factor
  n_steps: 2048  #16
  nn_size: 64 
  learning_rate: 2.5e-4
  
  vf_coef: 0.50  #Value function coefficient for the loss calculation
  
  max_grad_norm: 0.5 #The maximum value for the gradient clipping
  lam: 0.95 # Factor for trade-off of bias vs variance for Generalized Advantage Estimator
  quality: 0.85
