  num_envs: 1
  
  total_timesteps: 10000000
  validate_every_timesteps: 10000
  verbose: 0

  tau: 0.005
  ent_coef: 0.00 # ent_coef: (float) Entropy coefficient for the loss calculation
  gamma: 0.99 #gamma: (float) Discount factor
  timesteps_per_batch: 128  #16
  policy_noise: 0.2
  learning_rate: 3.0e-4
  random_exploration: 0.00
  
  quality: 0.85
