  num_envs: 1
  # ent_coef: (float) Entropy coefficint for the loss calculation
  ent_coef: 0.00
  #gamma: (float) Discount factor
  total_timesteps: 10000000
  validate_every_timesteps: 10000
  gamma: 0.99
  timesteps_per_batch: 16
  nn_size: 256
  learning_rate: 3.e-4
  verbose: 1

  #vf_coef: (float) Value function coefficient for the loss calculation
  vf_coef: 0.5

  #max_grad_norm: (float) The maximum value for the gradient clipping
  max_grad_norm: 0.5

  #am: (float) Factor for trade-off of bias vs variance for Generalized Advantage Estimator
  lam: 0.98
  quality: 0.85

