  num_envs : 1
  # ent_coef: (float) Entropy coefficient for the loss calculation
  ent_coef: 0.00
  #gamma: (float) Discount factor
  total_timesteps: 300000000
  validate_every_timesteps: 30000
  gamma: 0.9
  timesteps_per_batch: 128
  nn_size: 128
  learning_rate: 2.5e-4
  verbose: 0

  #vf_coef: (float) Value function coefficient for the loss calculation
  vf_coef: 0.5

  #max_grad_norm: (float) The maximum value for the gradient clipping
  max_grad_norm: 0.5

  #am: (float) Factor for trade-off of bias vs variance for Generalized Advantage Estimator
  lam: 0.90
  quality : 0.75