seed: 1


environment:
  render: 0
  # render_every_n_resets:  2000
  render_every_n_mins: 10
  
  speed_control: False

  simulation_dt: 0.00125
  control_dt: 0.01 # 0.01
  max_time: 5.0

  curruclum:
    use_curruclum: True
    curruclum_step_init: 13
    curruclum_step_max: 13
    ball_pose_disp_max: [[0,0,0],[0, 0, 0],[0.00,0.00,0.01], [0.01,0.01,0.01]   ,[0.02,0.02,0.02],  [0.02,0.02,0.04],  [0.02,0.02, 0.04],    [0.02,0.02,0.06],    [0.02,0.02,0.08],    [0.02,0.02,0.12],    [0.03,0.03,0.20],   [0.05,0.05,0.30],    [0.05,0.05,0.60],   [0.05,0.05,0.90]]
    ball_pose_disp_min: [[0,0,0],[0, 0, 0],[0.00,0.00,0.00], [-0.01,-0.01,0.01],[-0.02,-0.02,0.02],[-0.02,-0.02,0.02],[-0.02,-0.02, 0.02],  [-0.02,-0.02, 0.03], [-0.02,-0.02, 0.04], [-0.02,-0.02, 0.06], [-0.03,-0.03, 0.1], [-0.05,-0.05, 0.2],  [-0.06,-0.06, 0.3], [-0.06,-0.06, 0.4]]
    #                       1        2            3                   4                   5                 6                 7                       8                     9                     10              11                   12                   13                  14          
    pose: [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
